config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  resources :products do 
    resources :flags, shallow: true
  end
  
  resources :owners
  resources :flags

end

app/models/flag.rb
class Flag < ActiveRecord::Base
  belongs_to :product
  
  REASONS = ['Inappropriate', 'Not helpful','Wrong tags','Spam']

  validates_inclusion_of :reason, :in => REASONS,
                         :message => "%{value} must be included in #{REASONS.join(',')}"


  def valid_reasons
    REASONS
  end


end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :products
  validates_uniqueness_of :edmodo_id
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :owner
  has_many :flags
  
  accepts_nested_attributes_for :flags, reject_if: proc { |attributes| attributes['reason'].blank? }
  validates_uniqueness_of :edmodo_url

  searchable do
    string :title 
    text :long_desc_html
  end

  def full_url
    "https://spotlight.edmodo.com/product/#{self.edmodo_url}" 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController

  # GET /flags
  # GET /flags.json
  def index
    @flags = Flag.select("distinct product_id, reason")
    @flag_products = @flags.group_by{|f| f.product}.to_a
    @flag_products = Kaminari.paginate_array(@flag_products, total_count: @flag_products.length).page(params[:page]).per(12)
  end

  def show 
  end

  # GET /products/1/flags
  # GET /products/1/flags.json
  def new
    @product = Product.find(params[:product_id])
    @flags = @product.flags.build
  end

  def edit
  end

  # POST /products/1/flags
  # POST /products/1/flags.json
  def create
    @product = Product.find(params[:product_id])

    params[:flags][:reasons].each do |reason|
       @flag = @product.flags.build(reason: reason)
       @flag.save
    end

    respond_to do |format|
      if @flag.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @flag.errors.full_messages, 
                            status: :unprocessable_entity }
      end
    end
  end

  def create_multiple
    @product = Product.find(params[:product_id])

    @flag = @product.flags.build(flag_params)
  end


  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @flag.destroy
    respond_to do |format|
      format.html { redirect_to flags_url, notice: 'Flag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_flag
    @flag = Flag.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def flag_params
    params.require(:flags).permit(:product_id, :reason)
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:first_name, :last_name, :store_url, :edmodo_url, :edmodo_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @search = Product.search do 
      fulltext params[:search]
      paginate(page: params[:page], per_page: 12)
    end
    @products = @search.results
    #@products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :img_path, :seller_thumb_url, :edmodo_url, :price, :currency, :avg_rating, :num_raters, :long_desc_html, :owner_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/flags/_dialog.html.erb
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="static" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/flags/_form.html.erb
<%= form_for([@product, @flags], remote: true, :html => { :role => "form" }) do |f| %>
<div id="response">
</div>
 
<div class="row">
 <div class="col-sm-6">
  <div class="form-group">
    <% for reason in Flag::REASONS %>
      <div class="checkbox">
	    <label>
        <%= check_box_tag 'flags[reasons][]', reason %> 
   
    		<span class="push-xs-left"><%= reason %><span>
	    	
	    	</label>
		</div>
    <% end %>
 

   <%= f.submit  "Save", :class => "btn btn-primary" %>
 </div>
</div>
</div>
<% end %>

app/views/flags/_page_nav.html.erb
<nav>
  <ul class="pager">
    <li><%= link_to_previous_page @flag_products,'Prev Page' %></li>
    <li> <%= link_to_next_page @flag_products, 'Next Page' %></li>
  </ul>
</nav>

app/views/flags/create.js.erb
$('#dialog').modal('toggle');

app/views/flags/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'page_nav' %>


<% paginate @flag_products %>
<% @flag_products.each_slice(3) do | flag_products| %>
  
  <div class = "card-deck">
    <% flag_products.each do |product,flags| %>
      
     
     <div class = "card">
      <div class = "card-block">
        <h4 class="card-title push-xs-left"><%= product.title %></h4>
        <a href = "<%= product.full_url %>" target="_blank">
          <img class="card-image" src= "<%= product.img_path %>" />
        </a>
      </div>
      <div class= "card-block">
      <ul class="list-group list-group-flush">
      <% for flag in flags %>
        <li class="list-group-item"><%= flag.reason %></li>
      <% end %>
       </ul>
     </div>

    </div><!-- end card-->
    
    <% end %>

  </div><!-- end deck -->

<% end %>


<%= render 'page_nav' %>

app/views/flags/new.html.erb
<%= render 'form' %>

app/views/flags/new.js.erb
// Add the dialog title
$('#dialog h3').html("Add New Flag(s)");
 
// Render the new form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
	  $('.first_input').focus();
  })

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="Anna Selonick">
		<title>Edmodo Search</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

	</head>
	<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
		<nav class="navbar navbar-full navbar-dark bg-inverse">

			<a class="navbar-brand" href="/">Edmodo Search</a>
			 <ul class="nav navbar-nav">
			    <li class="nav-item">
			      <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
			    </li>
			   	<li class="nav-item">
			      <a class="nav-link" href="/flags">Flags</a>
			    </li>
			 </ul>
		

		</nav>
		<div class ="container">
			<div class = "row">
				<%= yield %>
			</div>
		</div>
</body>
</html>

app/views/owners/_form.html.erb
<%= form_for(@owner) do |f| %>
  <% if @owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% @owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :store_url %><br>
    <%= f.text_field :store_url %>
  </div>
  <div class="field">
    <%= f.label :edmodo_url %><br>
    <%= f.text_field :edmodo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form' %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Owners</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Store url</th>
      <th>Edmodo url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.first_name %></td>
        <td><%= owner.last_name %></td>
        <td><%= owner.store_url %></td>
        <td><%= owner.edmodo_url %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form' %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @owner.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @owner.last_name %>
</p>

<p>
  <strong>Store url:</strong>
  <%= @owner.store_url %>
</p>

<p>
  <strong>Edmodo url:</strong>
  <%= @owner.edmodo_url %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :img_path %><br>
    <%= f.text_field :img_path %>
  </div>
  <div class="field">
    <%= f.label :seller_thumb_url %><br>
    <%= f.text_field :seller_thumb_url %>
  </div>
  <div class="field">
    <%= f.label :edmodo_url %><br>
    <%= f.text_field :edmodo_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.number_field :currency %>
  </div>
  <div class="field">
    <%= f.label :avg_rating %><br>
    <%= f.number_field :avg_rating %>
  </div>
  <div class="field">
    <%= f.label :num_raters %><br>
    <%= f.number_field :num_raters %>
  </div>
  <div class="field">
    <%= f.label :long_desc_html %><br>
    <%= f.text_area :long_desc_html %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.text_field :owner_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_page_nav.html.erb
<nav>
  <ul class="pager">
    <li><%= link_to_previous_page @products,'Prev Page' %></li>
    <li> <%= link_to_next_page @products, 'Next Page' %></li>
  </ul>
</nav>

app/views/products/_search.html.erb
<div class="row">

	<%= form_tag products_path, :method => :get do %>
	  <div class="form-group">
	  	<div class="search-bar col-sm-10">
	  		<%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Subject, Lesson, or Activity' %>
	  	</div>

	  	<%= submit_tag "Search", :name => nil, class: 'btn btn-primary col-xs-2' %>

	</div>
	<% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'search' %>

<%= render 'page_nav' %>

  <% paginate @products %>

  <% @products.each_slice(3) do |products| %>
  <div class = "card-deck">
    <% products.each do |product| %>
    <div class = "card">
      <div class="card-block">
        <h4 class="card-title push-xs-left"><%= product.title %>
        <%= link_to(("<i class='fa fa-flag'></i>").html_safe, new_product_flag_path(product), remote: true, class: "btn btn-danger pull-xs-right") %></h4>
      </div>
      <div class="card-block">
        <a href = "<%= product.full_url %>" target="_blank">
          <img class="card-image" src= "<%= product.img_path %>" />
        </a>
    <br/><br/>
        <div class="card-text">
          <% if product.price.to_i == 0 %>
          <span> Free </span>
          <%else%>
            <%= product.price %><%= product.currency %>
          <%end%>
        </div>

      <div class="card-text">
        <% if product.num_raters.to_i > 0 %>
          <% (product.avg_rating.to_i).times do %>
            <i class='fa fa-star'></i>
          <%end%>
          (<%= product.num_raters %>)
        <%else%>
        <span> No Reviews </span> 
        <% end %>
      </div>
    </div>
      <div class = "card-block">
        <img class = "thumbnail" src = "<%= product.seller_thumb_url %>"/>

        <!--   <span><%= product.long_desc_html %></span>-->
        <%if (!product.owner.nil?) %>
        <span class = "card-text"><%= product.owner.first_name %></span>
        <%if (product.owner.role != "publisher") %>
        <span class = "card-text"><%= product.owner.last_name %></span>
        <% end %>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
</div>
</div>
<%= render 'page_nav' %>

<%= render 'flags/dialog' %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Img path:</strong>
  <%= @product.img_path %>
</p>

<p>
  <strong>Seller thumb url:</strong>
  <%= @product.seller_thumb_url %>
</p>

<p>
  <strong>Edmodo url:</strong>
  <%= @product.edmodo_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @product.currency %>
</p>

<p>
  <strong>Avg rating:</strong>
  <%= @product.avg_rating %>
</p>

<p>
  <strong>Num raters:</strong>
  <%= @product.num_raters %>
</p>

<p>
  <strong>Long desc html:</strong>
  <%= @product.long_desc_html %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @product.owner %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>